name: Check CRAN status

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  # schedule:
  #   # Runs daily at 4:00 PM UTC (9:00 AM PST)
  #   - cron: '0 16 * * *'
  # allows for manually running of the check
  workflow_dispatch:

jobs:
  check_cran_status:
    runs-on: ubuntu-latest

    steps:
      - name: Get CRAN checks
        uses: flrsh-dev/cran-checks/check-pkg@main
        with:
          pkg: ecotox
